import 'server-only';
import { YoutubeTranscript } from 'youtube-transcript';

/**
 * 字幕片段
 */
export interface SubtitleSegment {
  start: number;  // 開始時間（秒）
  end: number;    // 結束時間（秒）
  text: string;   // 字幕文字
}

/**
 * 字幕抓取結果
 */
export interface SubtitleResult {
  available: boolean;
  language: string;
  isAutoGenerated: boolean;
  segments: SubtitleSegment[];
  totalDuration: number;  // 總時長（秒）
  error?: string;
}

/**
 * 從 YouTube URL 提取 Video ID
 */
function extractVideoId(url: string): string | null {
  const patterns = [
    /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/shorts\/)([a-zA-Z0-9_-]{11})/,
  ];

  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match && match[1]) {
      return match[1];
    }
  }

  return null;
}

/**
 * 抓取 YouTube 視頻字幕
 *
 * @param videoUrl - YouTube 視頻 URL
 * @param preferredLang - 優先語言（預設：zh-TW, zh-Hant, zh, en）
 */
export async function fetchSubtitles(
  videoUrl: string,
  preferredLang: string[] = ['zh-TW', 'zh-Hant', 'zh', 'en']
): Promise<SubtitleResult> {
  const videoId = extractVideoId(videoUrl);

  if (!videoId) {
    return {
      available: false,
      language: '',
      isAutoGenerated: false,
      segments: [],
      totalDuration: 0,
      error: '無效的 YouTube URL',
    };
  }

  try {
    // 嘗試按優先順序抓取字幕
    let transcript = null;
    let usedLang = '';
    let isAuto = false;

    for (const lang of preferredLang) {
      try {
        transcript = await YoutubeTranscript.fetchTranscript(videoId, { lang });
        usedLang = lang;
        break;
      } catch {
        // 該語言不可用，嘗試下一個
        continue;
      }
    }

    // 如果指定語言都失敗，嘗試抓取任何可用字幕
    if (!transcript) {
      try {
        transcript = await YoutubeTranscript.fetchTranscript(videoId);
        usedLang = 'auto';
        isAuto = true;
      } catch {
        // 完全沒有字幕
        return {
          available: false,
          language: '',
          isAutoGenerated: false,
          segments: [],
          totalDuration: 0,
          error: '此視頻沒有可用字幕',
        };
      }
    }

    if (!transcript || transcript.length === 0) {
      return {
        available: false,
        language: '',
        isAutoGenerated: false,
        segments: [],
        totalDuration: 0,
        error: '字幕內容為空',
      };
    }

    // 轉換為統一格式
    const segments: SubtitleSegment[] = transcript.map((item) => ({
      start: item.offset / 1000,  // 轉換為秒
      end: (item.offset + item.duration) / 1000,
      text: item.text,
    }));

    // 計算總時長
    const lastSegment = segments[segments.length - 1];
    const totalDuration = lastSegment ? lastSegment.end : 0;

    return {
      available: true,
      language: usedLang,
      isAutoGenerated: isAuto || usedLang === 'auto',
      segments,
      totalDuration,
    };
  } catch (error: any) {
    console.error('[Subtitle] 抓取字幕失敗:', error);

    // 處理特定錯誤
    if (error.message?.includes('disabled')) {
      return {
        available: false,
        language: '',
        isAutoGenerated: false,
        segments: [],
        totalDuration: 0,
        error: '此視頻已禁用字幕',
      };
    }

    if (error.message?.includes('private') || error.message?.includes('unavailable')) {
      return {
        available: false,
        language: '',
        isAutoGenerated: false,
        segments: [],
        totalDuration: 0,
        error: '此視頻為私人或不可用',
      };
    }

    return {
      available: false,
      language: '',
      isAutoGenerated: false,
      segments: [],
      totalDuration: 0,
      error: `抓取字幕失敗: ${error.message || '未知錯誤'}`,
    };
  }
}

/**
 * 將字幕片段合併為完整文字
 */
export function mergeSubtitleText(segments: SubtitleSegment[]): string {
  return segments.map((s) => s.text).join(' ');
}

/**
 * YouTube 視頻 Metadata
 */
export interface VideoMetadata {
  title: string;
  author: string;
  thumbnailUrl: string;
}

/**
 * 從 YouTube oEmbed API 抓取視頻 Metadata
 * （不需要 API Key）
 */
export async function fetchVideoMetadata(videoUrl: string): Promise<VideoMetadata | null> {
  try {
    const oembedUrl = `https://www.youtube.com/oembed?url=${encodeURIComponent(videoUrl)}&format=json`;
    const response = await fetch(oembedUrl);

    if (!response.ok) {
      console.error('[Metadata] oEmbed 請求失敗:', response.status);
      return null;
    }

    const data = await response.json();

    return {
      title: data.title || '',
      author: data.author_name || '',
      thumbnailUrl: data.thumbnail_url || '',
    };
  } catch (error) {
    console.error('[Metadata] 抓取失敗:', error);
    return null;
  }
}
